title: My first Blog 0.0
author: Jack12
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm trying build a blog with help of github. **Issue** me if u have any advice 0.0
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
